use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let source_path = manifest_dir.join("data/emoji.toml");
    println!("cargo:rerun-if-changed={}", source_path.display());

    let source = fs::read_to_string(&source_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", source_path.display()));
    let parsed = source
        .parse::<toml_edit::DocumentMut>()
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", source_path.display()));
    let phrases = parsed
        .get("phrases")
        .and_then(toml_edit::Item::as_table)
        .unwrap_or_else(|| panic!("{} must contain a [phrases] table", source_path.display()));

    let mut entries: Vec<(String, String)> = phrases
        .iter()
        .map(|(phrase, value)| {
            let emoji = value
                .as_str()
                .unwrap_or_else(|| panic!("emoji phrase {phrase:?} must map to a string"));
            if phrase.trim().is_empty() {
                panic!("emoji phrase keys must not be empty");
            }
            if phrase.ends_with(" emoji") || phrase.ends_with(" emojis") {
                panic!("emoji phrase {phrase:?} must omit the final trigger word");
            }
            if emoji.trim().is_empty() {
                panic!("emoji phrase {phrase:?} maps to an empty value");
            }
            (phrase.to_string(), emoji.to_string())
        })
        .collect();
    entries.sort_unstable_by(|(left, _), (right, _)| left.cmp(right));

    let max_phrase_words = entries
        .iter()
        .map(|(phrase, _)| phrase.split_whitespace().count())
        .max()
        .unwrap_or(0);

    let mut generated = String::new();
    generated.push_str("// @generated by crates/azad-text/build.rs from data/emoji.toml\n");
    generated.push_str("// Do not edit by hand.\n\n");
    generated.push_str(&format!(
        "pub(crate) const MAX_EMOJI_PHRASE_WORDS: usize = {max_phrase_words};\n"
    ));
    generated.push_str("#[cfg(test)]\n");
    generated.push_str(&format!(
        "pub(crate) const EMOJI_PHRASE_COUNT: usize = {};\n\n",
        entries.len()
    ));
    generated.push_str(
        "pub(crate) static EMOJI_PHRASES: phf::Map<&'static str, &'static str> = phf::phf_map! {\n",
    );
    for (phrase, emoji) in entries {
        generated.push_str(&format!("    {phrase:?} => {emoji:?},\n"));
    }
    generated.push_str("};\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("emoji_phrases.rs");
    if fs::read_to_string(&out_path).ok().as_deref() != Some(generated.as_str()) {
        fs::write(&out_path, generated)
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
    }
}
